global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  # ============================================
  # AKASH TRAINER METRICS
  # ============================================
  - job_name: akash-trainer
    metrics_path: /metrics
    scrape_interval: 5s

    static_configs:
      - targets:
          - 'provider.h100.ams.val.akash.pub:32445'

        labels:
          platform: akash
          gpu: h100
          exporter: custom-trainer

  # ============================================
  # AWS TRAINER METRICS
  # ============================================
  - job_name: aws-trainer
    metrics_path: /metrics
    scrape_interval: 5s

    static_configs:
      - targets:
          - '13.42.50.165:8000'

        labels:
          platform: aws
          gpu: h100
          exporter: custom-trainer

  # ============================================
  # PUSHGATEWAY
  # ============================================
  - job_name: pushgateway
    honor_labels: true

    static_configs:
      - targets:
          - 'pushgateway:9091'